"""threat detection: events, findings, rules, alerts, incidents

Revision ID: 0d18372dac4d
Revises: 944065886673
Create Date: 2026-09-09 22:50:34.274174
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0d18372dac4d'
down_revision: str | None = '944065886673'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_rules',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('default_severity', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_detection_rules'))
    )
    op.create_table('incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('cohesion_score', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('alert_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_status'), ['status'], unique=False)

    op.create_table('verification_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('envelope_type', sa.String(length=16), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('algo', sa.String(length=64), nullable=True),
    sa.Column('hash_alg', sa.String(length=16), nullable=True),
    sa.Column('key_type', sa.String(length=16), nullable=True),
    sa.Column('key_bits', sa.Integer(), nullable=True),
    sa.Column('curve', sa.String(length=32), nullable=True),
    sa.Column('signer_subject', sa.Text(), nullable=True),
    sa.Column('signer_spki_sha256', sa.String(length=64), nullable=True),
    sa.Column('signing_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tsa_present', sa.Boolean(), nullable=False),
    sa.Column('chain_status', sa.String(length=16), nullable=True),
    sa.Column('revocation_status', sa.String(length=16), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('submitter_id', sa.String(length=36), nullable=True),
    sa.Column('submitter_ip_hash', sa.String(length=64), nullable=True),
    sa.Column('payload_sha256', sa.String(length=64), nullable=True),
    sa.Column('signature_sha256', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], name=op.f('fk_verification_events_submitter_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_events'))
    )
    with op.batch_alter_table('verification_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_events_payload_sha256'), ['payload_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_events_signature_sha256'), ['signature_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_events_signer_spki_sha256'), ['signer_spki_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_events_submitter_ip_hash'), ['submitter_ip_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_events_verdict'), ['verdict'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('rule_codes', sa.JSON(), nullable=False),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('triaged_by', sa.String(length=36), nullable=True),
    sa.Column('triaged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_alerts_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['verification_events.id'], name=op.f('fk_alerts_event_id_verification_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_alerts_incident_id_incidents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triaged_by'], ['users.id'], name=op.f('fk_alerts_triaged_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_incident_id'), ['incident_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('rule_code', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['verification_events.id'], name=op.f('fk_findings_event_id_verification_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings'))
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_rule_code'), ['rule_code'], unique=False)

    op.create_table('alert_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_alert_notes_alert_id_alerts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_alert_notes_author_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_notes'))
    )
    with op.batch_alter_table('alert_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_notes_alert_id'), ['alert_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_notes_alert_id'))

    op.drop_table('alert_notes')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_rule_code'))
        batch_op.drop_index(batch_op.f('ix_findings_event_id'))

    op.drop_table('findings')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_incident_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_event_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('verification_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_events_verdict'))
        batch_op.drop_index(batch_op.f('ix_verification_events_submitter_ip_hash'))
        batch_op.drop_index(batch_op.f('ix_verification_events_signer_spki_sha256'))
        batch_op.drop_index(batch_op.f('ix_verification_events_signature_sha256'))
        batch_op.drop_index(batch_op.f('ix_verification_events_payload_sha256'))
        batch_op.drop_index(batch_op.f('ix_verification_events_created_at'))

    op.drop_table('verification_events')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_status'))

    op.drop_table('incidents')
    op.drop_table('detection_rules')
    # ### end Alembic commands ###
