"""cryptographic core: certificates, trust store

Revision ID: 944065886673
Revises: 4d79d868c15e
Create Date: 2026-09-09 22:25:06.560384
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '944065886673'
down_revision: str | None = '4d79d868c15e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('spki_sha256', sa.String(length=64), nullable=False),
    sa.Column('fingerprint_sha256', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('issuer', sa.Text(), nullable=False),
    sa.Column('serial_hex', sa.String(length=80), nullable=False),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=False),
    sa.Column('not_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sig_algo', sa.String(length=64), nullable=False),
    sa.Column('key_type', sa.String(length=16), nullable=False),
    sa.Column('key_bits', sa.Integer(), nullable=True),
    sa.Column('curve', sa.String(length=32), nullable=True),
    sa.Column('is_ca', sa.Boolean(), nullable=False),
    sa.Column('self_signed', sa.Boolean(), nullable=False),
    sa.Column('times_seen', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('pem', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificates'))
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificates_fingerprint_sha256'), ['fingerprint_sha256'], unique=True)
        batch_op.create_index(batch_op.f('ix_certificates_spki_sha256'), ['spki_sha256'], unique=False)

    op.create_table('ca_allowlist_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_pattern', sa.String(length=255), nullable=False),
    sa.Column('issuer_spki_sha256', sa.String(length=64), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('added_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_ca_allowlist_entries_added_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ca_allowlist_entries'))
    )
    op.create_table('trust_anchors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('spki_sha256', sa.String(length=64), nullable=False),
    sa.Column('fingerprint_sha256', sa.String(length=64), nullable=False),
    sa.Column('not_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('pem', sa.Text(), nullable=False),
    sa.Column('added_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_trust_anchors_added_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trust_anchors')),
    sa.UniqueConstraint('fingerprint_sha256', name=op.f('uq_trust_anchors_fingerprint_sha256'))
    )
    with op.batch_alter_table('trust_anchors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trust_anchors_spki_sha256'), ['spki_sha256'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trust_anchors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trust_anchors_spki_sha256'))

    op.drop_table('trust_anchors')
    op.drop_table('ca_allowlist_entries')
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificates_spki_sha256'))
        batch_op.drop_index(batch_op.f('ix_certificates_fingerprint_sha256'))

    op.drop_table('certificates')
    # ### end Alembic commands ###
