"""quantum-inspired: runs, exposure scores

Revision ID: c328b84cdabc
Revises: 0d18372dac4d
Create Date: 2026-09-09 23:15:19.535170
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c328b84cdabc'
down_revision: str | None = '0d18372dac4d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quantum_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_type', sa.String(length=24), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('wall_ms', sa.Float(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('input_ref', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_quantum_runs_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quantum_runs'))
    )
    with op.batch_alter_table('quantum_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quantum_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_quantum_runs_run_type'), ['run_type'], unique=False)

    op.create_table('quantum_exposure_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('spki_sha256', sa.String(length=64), nullable=True),
    sa.Column('algo', sa.String(length=32), nullable=True),
    sa.Column('key_type', sa.String(length=16), nullable=True),
    sa.Column('key_bits', sa.Integer(), nullable=True),
    sa.Column('curve', sa.String(length=32), nullable=True),
    sa.Column('qes', sa.Float(), nullable=False),
    sa.Column('band', sa.String(length=16), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['verification_events.id'], name=op.f('fk_quantum_exposure_scores_event_id_verification_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quantum_exposure_scores'))
    )
    with op.batch_alter_table('quantum_exposure_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quantum_exposure_scores_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_quantum_exposure_scores_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quantum_exposure_scores_qes'), ['qes'], unique=False)
        batch_op.create_index(batch_op.f('ix_quantum_exposure_scores_spki_sha256'), ['spki_sha256'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quantum_exposure_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quantum_exposure_scores_spki_sha256'))
        batch_op.drop_index(batch_op.f('ix_quantum_exposure_scores_qes'))
        batch_op.drop_index(batch_op.f('ix_quantum_exposure_scores_event_id'))
        batch_op.drop_index(batch_op.f('ix_quantum_exposure_scores_created_at'))

    op.drop_table('quantum_exposure_scores')
    with op.batch_alter_table('quantum_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quantum_runs_run_type'))
        batch_op.drop_index(batch_op.f('ix_quantum_runs_created_at'))

    op.drop_table('quantum_runs')
    # ### end Alembic commands ###
