"""ml model registry

Revision ID: e7c38870d1e3
Revises: c328b84cdabc
Create Date: 2026-09-09 23:39:50.655134
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e7c38870d1e3'
down_revision: str | None = 'c328b84cdabc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_models',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('algo', sa.String(length=24), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('feature_schema_version', sa.Integer(), nullable=False),
    sa.Column('n_train', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('artifact_path', sa.String(length=255), nullable=False),
    sa.Column('artifact_sha256', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('trained_by', sa.String(length=36), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trained_by'], ['users.id'], name=op.f('fk_ml_models_trained_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_models'))
    )
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_models_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_models_trained_at'), ['trained_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_models_trained_at'))
        batch_op.drop_index(batch_op.f('ix_ml_models_is_active'))

    op.drop_table('ml_models')
    # ### end Alembic commands ###
